; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; esp32-s3-devkitc-1 board def defaults to the N8 variant (8MB flash, no
; PSRAM); override for the actual N16R8 hardware (16MB flash, 8MB Octal PSRAM)
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.psram_type = opi
board_build.filesystem = littlefs

build_flags =
    -DBOARD_HAS_PSRAM
